In [4]:
# homework

import numpy as np

ls=[12.23, 13.32, 100, 36.32]
arr=np.array(ls)
print(arr)
print(ls)

[ 12.23  13.32 100.    36.32]
[12.23, 13.32, 100, 36.32]


In [7]:
# SECOND PUZZLE #Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# third puzzle 
#3. Null Vector (10) & Update Sixth Value, Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
import numpy as np
nul_vektor=np.zeros(10)
print(nul_vektor)
nul_vektor[6]=11
print(nul_vektor)

 


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [11]:
import numpy as np
x=np.zeros(15)
print(x)
x[7]=12
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0.  0. 12.  0.  0.  0.  0.  0.  0.  0.]


In [ ]:
# 4   Write a NumPy program to create an array with values ranging from 12 to 38.
import numpy as np
x=np.arange(12,38,1)
print(x)
 


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [20]:
# 5 puzzle Convert Array to Float Type
#Write a NumPy program to convert an array to a floating type.
import numpy as np
ar=np.array([1,2,3,4])
ar
ar_float=ar.astype(float)
print(ar_float)
x=type(ar_float)
print(x)
print(ar_float.dtype)



[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64


In [4]:
# puzzle 6
#6. Celsius to Fahrenheit Conversion
#Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

import numpy as np
c=np.array([ [0, 12, 45.21, 34, 99.91, 0.] ,[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

])
f=c*9/5+32
print(c)

print(f)




[[  0.    12.    45.21  34.    99.91   0.  ]
 [-17.78 -11.11   7.34   1.11  37.73   0.  ]]
[[ 3.20000e+01  5.36000e+01  1.13378e+02  9.32000e+01  2.11838e+02
   3.20000e+01]
 [-4.00000e-03  1.20020e+01  4.52120e+01  3.39980e+01  9.99140e+01
   3.20000e+01]]


In [8]:
# puzzle 7
# 7. Append Values to Array (Do self-tudy)
# Write a NumPy program to append values to the end of an array.
import numpy as np
x=np.array([10,20,30])
x
b=np.append(x, [40, 50, 60,70,80,90])
print(x)
print(b)


[10 20 30]
[10 20 30 40 50 60 70 80 90]


In [17]:
# puzzle 8
# Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.
import numpy as np
arr=np.random.randint(0, 101, size=10)
print(arr)
m=np.mean(arr)
md=np.median(arr)
st=np.std(arr)
print(arr)
print(m)
print(md)
print(st)


[18 97 99 23 51 40 90  6 41 81]
[18 97 99 23 51 40 90  6 41 81]
54.6
46.0
32.909573075322626


In [ ]:
# puzzle 9 Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
array = np.random.rand(10, 10)
min_value = np.min(array)
max_value = np.max(array)
print("Generated 10x10 array:\n", array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)





Generated 10x10 array:
 [[0.74088075 0.9550977  0.94758938 0.00848061 0.03203597 0.26745007
  0.17643236 0.73985469 0.60883038 0.40346626]
 [0.64020336 0.32722756 0.68935072 0.42827187 0.67945631 0.03907975
  0.76475174 0.48903781 0.18172704 0.65092555]
 [0.76840752 0.87078618 0.4256628  0.2674196  0.37189057 0.24943941
  0.60933598 0.8090179  0.87000053 0.55246063]
 [0.99366064 0.1737169  0.64184004 0.43024733 0.88617873 0.24759563
  0.4200956  0.57613407 0.61528406 0.01365143]
 [0.25942822 0.11393088 0.79468867 0.82144717 0.26415199 0.70326135
  0.14766801 0.51326761 0.01903419 0.56288935]
 [0.58196473 0.1210385  0.85234478 0.73057502 0.59780435 0.71986591
  0.53502157 0.8000771  0.79050609 0.15678903]
 [0.05489661 0.20205007 0.64054461 0.56242335 0.79174374 0.47861656
  0.22666931 0.75312616 0.38553702 0.93158275]
 [0.61861324 0.41771654 0.31444703 0.2671528  0.45038174 0.32908982
  0.72006113 0.75425261 0.2576727  0.35638625]
 [0.70576321 0.79285847 0.05722475 0.37492957 0.67298522

In [19]:
# puzzle 10 Create a 3x3x3 array with random values.
import numpy as np
array = np.random.rand(3, 3, 3)

print("3x3x3 random array:\n", array)



3x3x3 random array:
 [[[0.49841607 0.43102151 0.67033106]
  [0.33947888 0.20985949 0.20220947]
  [0.84862691 0.48429221 0.37913431]]

 [[0.58334737 0.3000398  0.14938626]
  [0.37421177 0.93493565 0.52890914]
  [0.27888295 0.27876103 0.56906181]]

 [[0.98058223 0.02403895 0.40051024]
  [0.36471437 0.93259158 0.87224617]
  [0.6643516  0.8515925  0.73178658]]]
